name: enviro_agri_manager 
description: "Đây là ứng dụng Flutter được thiết kế để quản lý danh mục điện tử dùng chung cho ngành Nông nghiệp và Môi trường. Hệ thống cung cấp các chức năng quản lý sản phẩm, theo dõi dữ liệu môi trường, và báo cáo thống kê."
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  fl_chart: ^0.69.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.5.6
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
